export enum ActionType {
  GET_POST_COMMENTS_PENDING = 'GET_POST_COMMENTS_PENDING',
  GET_POST_COMMENTS_SUCCESS = 'GET_POST_COMMENTS_SUCCESS',
  GET_POST_COMMENTS_FAIL = 'GET_POST_COMMENTS_FAIL',
  LOGIN_USER = 'LOGIN_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  RESET_LOGIN_STATES = 'RESET_LOGIN_STATES'
}
