export enum ActionType {
  GETTING_POST = 'GETTING_POST',
  GETTING_POST_SUCCESS = 'GETTING_POST_SUCCESS',
  GETTING_POST_FAIL = 'GETTING_POST_FAIL',
  
  ADDING_POST = 'ADDING_POST',
  ADD_POST_MODAL_TOGGLE = 'ADD_POST_MODAL_TOGGLE',
  ADDING_POST_SUCCESS = 'ADDING_POST_SUCCESS',
  ADDING_POST_FAIL = 'ADDING_POST_FAIL',

  UPDATING_POST = 'UPDATING_POST',
  UPDATING_POST_SUCCESS = 'UPDATING_POST_SUCCESS',
  UPDATING_POST_FAIL = 'UPDATING_POST_FAIL',
  
  RESET_POST_STATES = 'RESET_POST_STATES',

  DELETE_POST_MODAL_TOGGLE = 'DELETE_POST_MODAL_TOGGLE',
  DELETING_POST = 'DELETING_POST',
  DELETING_POST_SUCCESS = 'DELETING_POST_SUCCESS',
  DELETING_POST_FAIL = 'DELETING_POST_FAIL',
  FILTER_POST = 'FILTER_POST',
      

  LOGIN_USER = 'LOGIN_USER',
  LOGOUT_USER = 'LOGOUT_USER',
  RESET_LOGIN_STATES = 'RESET_LOGIN_STATES'
}
